version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: full
      POSTGRES_PASSWORD: dtrm65
      POSTGRES_DB: testdb
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data